name: Déploiement FTP vers ByetHost
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0  # ✅ Action officielle et maintenue
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_DIRECTORY }}
