name: Déploiement FTP vers ByetHost
on:
  push:
    branches: [ main ]  # Se déclenche sur un push vers "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Récupère le code GitHub

      - name: Déployer via FTP
        uses: samkirsch/ftp-deploy@v2.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Dossier local à envoyer (racine du dépôt)
          server-dir: ${{ secrets.FTP_DIRECTORY }}  # Dossier distant sur ByetHost
